### ISSUE TITLE
example does not work with traefik 2.5.3

### ISSUE THREAD

**Issue by vtacquet** [dclairac/traefik-plugin-headers#3]
```
http:
  routers:
    dns:
      entrypoints: "in80"
      rule: "PathPrefix(`/dns`)"
      middlewares:
        - traefik-plugin-headers
      service: dns
  middlewares:
    traefik-plugin-headers:
      plugin:
        defaultHeaders:
          - headerChange:
            header: 'header-to-delete'
            req: true
            action: 'unset'
        rules:
          - rule:
            name: 'Only for png or js'
            regexp: '(png|js)$'
            responseHeaders:
              Expires:
                value: '@DT_ADD#86400@'
                action: 'set'
          - rule:
            name: 'If no rules match'
            regexp: 'NO_MATCH'
            requestHeaders:
              header-to-delete:
                action: 'unset'
  services:
    dns:
      loadbalancer:
        servers:
          - url: "http://192.168.2.1:80"
```

time="2021-11-02T08:15:11+01:00" level=error msg="plugin: invalid configuration: no configuration or too many plugin definition" entryPointName=in80 routerName=dns@file

![CleanShot 2021-11-02 at 08 22 51](https://user-images.githubusercontent.com/5128967/139802974-04945d3c-c8ff-4038-a356-928778ef0b77.png)
